title: Sprechen Sie Denglish
description: German for the rest of us
permalink: ':title/'
# baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "http://www.sprechensiedenglish.com"
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Sprechen Sie Denglish? # add your name
author-img: flags.jpg # add your photo
about-author: German for the rest of us # add description
twitter: # add your Twitter handle
facebook: # add your Facebook handle
github: artemsheludko # add your Github handle
linkedin: # add your Linkedin handle
email: # add your Email address

# Disqus
discus-identifier: sprechen-sie-denglish

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 6
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
